#template/nginx-server-block.conf

server {
    listen 8081;
    server_name 180.93.32.205;

    root /var/www/devops-hackathon-de008-dokhacquyen/src
    index index.html;

    access_log /var/log/nginx/dokhacquyen-k24cntt4.access.log;
    error_log /var/log/nginx/dokhacquyen-k24cntt4.error.log;

    location / {
        <ALLOW_OVERRIDE>;
        try_files $uri $uri/ =404;
    }
}